name: vue-CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: install
      run: |
        yarn install
        yarn build
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
