name: vue-CI

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install
        run: |
          yarn install
          yarn build
      # Runs a set of commands using the runners shell
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    #   dockerlogin--usernameanyhoo
